# NumPy Complete Hands-On Practice Notebook

**Goal:** Cover the core NumPy library through real implementation.

### How to use
1. Read the concept.
2. Run the real implementation.
3. Solve all 5 practice questions yourself.
4. Complete the final capstone projects.

> Prefer NumPy vectorized operations instead of Python loops whenever practical.


In [1]:
import numpy as np
print('NumPy version:', np.__version__)

NumPy version: 2.5.3


## 1. Creating NumPy Arrays

NumPy arrays are created mainly with `np.array()`, `np.zeros()`, `np.ones()`, `np.full()`, `np.arange()`, and `np.linspace()`.

### Real implementation

In [2]:
# Real implementation: create a small sales dataset
sales = np.array([1200, 1500, 1100, 1800, 2100])
print(sales)

[1200 1500 1100 1800 2100]


### Practice — 5 Questions

**1.** Create a NumPy array containing the temperatures `[32, 35, 31, 29, 36]`.
**2.** Create an array of 10 zeros.
**3.** Create a 3x4 array filled with ones.
**4.** Create numbers from 10 to 50 with a step of 5 using NumPy.
**5.** Create 6 equally spaced values between 0 and 1 using `linspace`.

In [3]:
# Practice 1: Create a NumPy array containing the temperatures `[32, 35, 31, 29, 36]`.
# Write your solution here
import numpy as np

a = np.array([32, 35, 31, 29, 36])
a


array([32, 35, 31, 29, 36])

In [4]:
# Practice 2: Create an array of 10 zeros.
# Write your solution here
b=np.zeros(10)
b

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
# Practice 3: Create a 3x4 array filled with ones.
# Write your solution here
c = np.ones((3, 4))
c

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
# Practice 4: Create numbers from 10 to 50 with a step of 5 using NumPy.
# Write your solution here
d=np.arange(10, 51, 5)
d

array([10, 15, 20, 25, 30, 35, 40, 45, 50])

In [7]:
# Practice 5: Create 6 equally spaced values between 0 and 1 using `linspace`.
# Write your solution here
e=np.linspace(0, 1, 6)
e=y
print("equally spaced values:", e)

NameError: name 'y' is not defined

## 2. Array Attributes

Important attributes include `.ndim`, `.shape`, `.size`, `.dtype`, and `.itemsize`.

### Real implementation

In [ ]:
data = np.array([[10,20,30],[40,50,60]])
print("dimensions:", data.ndim)
print("shape:", data.shape)
print("size:", data.size)
print("dtype:", data.dtype)
print("itemsize:", data.itemsize)

dimensions: 2
shape: (2, 3)
size: 6
dtype: int64
itemsize: 8


### Practice — 5 Questions

**1.** Create a 3x4 array and print its dimensions, shape and size.
**2.** Create a 1D array of 20 integers and inspect its attributes.
**3.** Create a 2x3x4 array and determine its number of dimensions.
**4.** Compare the `size` of two arrays with different shapes.
**5.** Find the memory size per element of a float array.

In [ ]:
# Practice 1: Create a 3x4 array and print its dimensions, shape and size.
# Write your solution here
c = np.ones((3, 4))
y=np.ndim(c)
print("dimensions:", y)
z=np.shape(c)
print("shape:", z)
s=np.size(c)
print("size:", s)   

dimensions: 2
shape: (3, 4)
size: 12


In [ ]:
# Practice 2: Create a 1D array of 20 integers and inspect its attributes.
# Write your solution here
aa = np.arange(20)
aa
print("dimensions:", aa.ndim)
print("shape:", aa.shape)
print("size:", aa.size)

dimensions: 1
shape: (20,)
size: 20


In [ ]:
# Practice 3: Create a 2x3x4 array and determine its number of dimensions.
# Write your solution here
bb = np.ones((2, 3, 4))
bb
print("dimensions:", bb.ndim)   


dimensions: 3


In [ ]:
# Practice 4: Compare the `size` of two arrays with different shapes.
# Write your solution here
cc = np.ones((2, 3))
dd = np.ones((3, 2))
print("size of cc:", cc.size)
print("size of dd:", dd.size)

size of cc: 6
size of dd: 6


In [ ]:
# Practice 5: Find the memory size per element of a float array.
# Write your solution here
ee = np.array([1.0, 2.0, 3.0], dtype=np.float64)
print("itemsize of ee:", ee.itemsize, "bytes")

itemsize of ee: 8 bytes


## 3. Data Types (`dtype`)

NumPy supports fixed numeric types such as `int32`, `int64`, `float32`, `float64`, and boolean values.

### Real implementation

In [ ]:
a = np.array([1,2,3], dtype=np.int32)
b = np.array([1.5,2.5,3.5], dtype=np.float32)
print(a.dtype, b.dtype)

int32 float32


### Practice — 5 Questions

**1.** Create an array using `int32`.
**2.** Create a `float64` array and convert it to `int32`.
**3.** Create a boolean array and inspect its dtype.
**4.** Convert string numbers `['10','20','30']` to integers.
**5.** Compare the item size of `int32` and `int64`.

In [ ]:
# Practice 1: Create an array using `int32`.
# Write your solution here
v=np.array([1, 2, 3], dtype=np.int32)
v

array([1, 2, 3], dtype=int32)

In [ ]:
# Practice 2: Create a `float64` array and convert it to `int32`.
# Write your solution here
g=np.array([1.5, 2.5, 3.5], dtype=np.float64)
h=g.astype(np.int32)
h

array([1, 2, 3], dtype=int32)

In [ ]:
# Practice 3: Create a boolean array and inspect its dtype.
# Write your solution here
r=np.array([True, False, True])
print("dtype of r:", r.dtype)

dtype of r: bool


In [ ]:
# Practice 4: Convert string numbers `['10','20','30']` to integers.
# Write your solution here
i=np.array(['10','20','30'])
j=i.astype(np.int32)
j

array([10, 20, 30], dtype=int32)

In [ ]:
# Practice 5: Compare the item size of `int32` and `int64`.
# Write your solution here
t = np.array([1, 2, 3], dtype=np.int32)
u = np.array([1, 2, 3], dtype=np.int64)
print("itemsize of t (int32):", t.itemsize, "bytes")
print("itemsize of u (int64):", u.itemsize, "bytes")

itemsize of t (int32): 4 bytes
itemsize of u (int64): 8 bytes


## 4. Indexing

Indexing accesses individual elements. NumPy uses zero-based indexing and supports multidimensional indexing.

### Real implementation

In [ ]:
marks = np.array([[78,85,92],[66,74,81],[90,88,95]])
print(marks[0,2])
print(marks[2,0])

### Practice — 5 Questions

**1.** Get the third element of `[10,20,30,40,50]`.
**2.** Get the last element without using its length.
**3.** From a 3x3 matrix, retrieve the center value.
**4.** Retrieve the value in row 2, column 3 of a matrix.
**5.** Replace one selected element with a new value.

In [ ]:
# Practice 1: Get the third element of `[10,20,30,40,50]`.
# Write your solution here
i=np.array([10,20,30,40,50])
i[2]

np.int64(30)

In [ ]:
# Practice 2: Get the last element without using its length.
# Write your solution here
o=np.array([10,20,30,40,50])
o[-1]

np.int64(50)

In [ ]:
# Practice 3: From a 3x3 matrix, retrieve the center value.
# Write your solution here
p=np.array([[1,2,3],[4,5,6],[7,8,9]])
p[1,1]

np.int64(5)

In [ ]:
# Practice 4: Retrieve the value in row 2, column 3 of a matrix.
# Write your solution here
op=np.array([[1,2,3],[4,5,6],[7,8,9]])
op[1,2]

np.int64(6)

In [ ]:
# Practice 5: Replace one selected element with a new value.
# Write your solution here
op[1,2] = 10
op

array([[ 1,  2,  3],
       [ 4,  5, 10],
       [ 7,  8,  9]])

## 5. Slicing

Slicing uses `start:stop:step` and works across dimensions.

### Real implementation

In [ ]:
sales = np.array([100,200,300,400,500,600])
print(sales[1:5])
print(sales[::2])

### Practice — 5 Questions

**1.** Get the first three elements.
**2.** Get the last three elements.
**3.** Get every second element.
**4.** Reverse an array using slicing.
**5.** From a 4x5 matrix, extract the middle 2x3 region.

In [ ]:
# Practice 1: Get the first three elements.
# Write your solution here
j=np.array([100,200,300,400,500,600])
j[:3]

array([100, 200, 300])

In [ ]:
# Practice 2: Get the last three elements.
# Write your solution here
j[3:]

array([400, 500, 600])

In [ ]:
# Practice 3: Get every second element.
# Write your solution here
j[::2]

array([100, 300, 500])

In [ ]:
# Practice 4: Reverse an array using slicing.
# Write your solution here
j[::-1]

array([600, 500, 400, 300, 200, 100])

In [ ]:
# Practice 5: From a 4x5 matrix, extract the middle 2x3 region.
# Write your solution here
k=np.array([[1,2,3,4,5],
            [6,7,8,9,10],
            [11,12,13,14,15],
            [16,17,18,19,20]])
k


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
k[1:3, 1:4]

array([[ 7,  8,  9],
       [12, 13, 14]])

## 6. Reshaping and Shape

`reshape()` changes the structure while preserving the number of elements. `shape` tells us the dimensions.

### Real implementation

In [ ]:
x = np.arange(1,13)
matrix = x.reshape(3,4)
print(matrix)
print(matrix.shape)

### Practice — 5 Questions

**1.** Reshape 12 numbers into 3x4.
**2.** Reshape 24 numbers into 2x3x4.
**3.** Convert a 5x6 matrix into 3x10.
**4.** Use `-1` to let NumPy infer one dimension.
**5.** Transpose a 3x4 matrix into a 4x3 matrix.

In [ ]:
# Practice 1: Reshape 12 numbers into 3x4.
# Write your solution here
l=np.arange(1,13)
l.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# Practice 2: Reshape 24 numbers into 2x3x4.
# Write your solution here
z = np.arange(1,25)
z.reshape(2,3,4)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [ ]:
# Practice 3: Convert a 5x6 matrix into 3x10.
# Write your solution here
x=np.arange(1,31).reshape(5,6)
x.reshape(3,10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [ ]:
# Practice 4: Use `-1` to let NumPy infer one dimension.
# Write your solution here
c = np.arange(1, 25).reshape(2, 3, 4)
c.reshape(3, -1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
# Practice 5: Transpose a 3x4 matrix into a 4x3 matrix.
# Write your solution here
v = np.arange(1, 13).reshape(3, 4)
v_transposed = v.T
v_transposed

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

## 7. Flattening and Ravel

`flatten()` returns a copy; `ravel()` generally returns a view when possible.

### Real implementation

In [ ]:
matrix = np.arange(1,10).reshape(3,3)
print(matrix.flatten())
print(matrix.ravel())

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


### Practice — 5 Questions

**1.** Flatten a 2x4 matrix.
**2.** Use `ravel()` on a 3D array.
**3.** Check the shape after flattening.
**4.** Demonstrate that flatten returns a separate array.
**5.** Modify a ravel result and investigate whether the original changes.

In [ ]:
# Practice 1: Flatten a 2x4 matrix.
# Write your solution here
b=np.arange(1,9).reshape(2,4)
b.flatten()


array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
# Practice 2: Use `ravel()` on a 3D array.
# Write your solution here
opp=np.arange(1, 25).reshape(2, 3, 4)
c=opp.ravel()
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [ ]:
# Practice 3: Check the shape after flattening.
# Write your solution here
ab=opp.shape
ab

(2, 3, 4)

In [ ]:
# Practice 4: Demonstrate that flatten returns a separate array.
# Write your solution here
ac=opp.flatten()
ac

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [ ]:
# Practice 5: Modify a ravel result and investigate whether the original changes.
# Write your solution here
ad=opp.ravel()
ad[0] = 100
print("Modified ravel result:", ad)
print("Original array after modifying ravel result:", opp)

Modified ravel result: [100   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24]
Original array after modifying ravel result: [[[100   2   3   4]
  [  5   6   7   8]
  [  9  10  11  12]]

 [[ 13  14  15  16]
  [ 17  18  19  20]
  [ 21  22  23  24]]]


## 8. Joining and Stacking

Use `concatenate()`, `vstack()`, and `hstack()` to combine arrays.

### Real implementation

In [8]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.concatenate([a,b]))
print(np.vstack([a,b]))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


### Practice — 5 Questions

**1.** Concatenate two 1D arrays.
**2.** Horizontally stack two arrays.
**3.** Vertically stack two arrays.
**4.** Combine two 2x3 matrices vertically.
**5.** Combine two compatible matrices horizontally.

In [9]:
# Practice 1: Concatenate two 1D arrays.
# Write your solution here
a=np.array([1,2,3])
b=np.array([4,5,6])
result = np.concatenate([a, b])
result

array([1, 2, 3, 4, 5, 6])

In [10]:
# Practice 2: Horizontally stack two arrays.
# Write your solution here
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
result = np.hstack([a, b])
result

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [11]:
# Practice 3: Vertically stack two arrays.
# Write your solution here
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
result = np.vstack([a, b])
result

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [12]:
# Practice 4: Combine two 2x3 matrices vertically.
# Write your solution here
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
result = np.vstack([a, b])
result

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [13]:
# Practice 5: Combine two compatible matrices horizontally.
# Write your solution here
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
result = np.hstack([a, b])
result

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

## 9. Splitting Arrays

`split()`, `array_split()`, `vsplit()`, and `hsplit()` divide arrays into smaller arrays.

### Real implementation

In [ ]:
x = np.arange(1,13)
parts = np.split(x, 3)
print(parts)

### Practice — 5 Questions

**1.** Split 12 values into 4 equal parts.
**2.** Split a 10-element array into 3 parts using `array_split`.
**3.** Split a 4x4 matrix into two row groups.
**4.** Split a 4x4 matrix into two column groups.
**5.** Extract three monthly groups from a 12-month dataset.

In [ ]:
# Practice 1: Split 12 values into 4 equal parts.
# Write your solution here


In [ ]:
# Practice 2: Split a 10-element array into 3 parts using `array_split`.
# Write your solution here


In [ ]:
# Practice 3: Split a 4x4 matrix into two row groups.
# Write your solution here


In [ ]:
# Practice 4: Split a 4x4 matrix into two column groups.
# Write your solution here


In [ ]:
# Practice 5: Extract three monthly groups from a 12-month dataset.
# Write your solution here


## 10. Copy vs View

A copy has independent data; a view shares the underlying data.

### Real implementation

In [ ]:
original = np.array([10,20,30,40])
view = original[1:3]
view[0] = 999
print(original)

copy = original.copy()
copy[0] = 111
print(original, copy)

### Practice — 5 Questions

**1.** Create a slice and test whether it shares data.
**2.** Create a true copy and modify it.
**3.** Use `.base` to inspect whether an array is a view.
**4.** Show a practical bug caused by modifying a view.
**5.** Write code that safely copies a dataset before transformation.

In [ ]:
# Practice 1: Create a slice and test whether it shares data.
# Write your solution here


In [ ]:
# Practice 2: Create a true copy and modify it.
# Write your solution here


In [ ]:
# Practice 3: Use `.base` to inspect whether an array is a view.
# Write your solution here


In [ ]:
# Practice 4: Show a practical bug caused by modifying a view.
# Write your solution here


In [ ]:
# Practice 5: Write code that safely copies a dataset before transformation.
# Write your solution here


## 11. Array Iteration

NumPy supports iteration over 1D and multidimensional arrays, although vectorized operations are usually preferred for performance.

### Real implementation

In [ ]:
matrix = np.array([[1,2,3],[4,5,6]])
for row in matrix:
    print(row)

### Practice — 5 Questions

**1.** Iterate through a 1D array.
**2.** Iterate through rows of a matrix.
**3.** Use `np.nditer()` on a 2D array.
**4.** Print each value of a 3D array.
**5.** Calculate a total using iteration, then solve the same task vectorized.

In [ ]:
# Practice 1: Iterate through a 1D array.
# Write your solution here


In [ ]:
# Practice 2: Iterate through rows of a matrix.
# Write your solution here


In [ ]:
# Practice 3: Use `np.nditer()` on a 2D array.
# Write your solution here


In [ ]:
# Practice 4: Print each value of a 3D array.
# Write your solution here


In [ ]:
# Practice 5: Calculate a total using iteration, then solve the same task vectorized.
# Write your solution here


## 12. Arithmetic Operations

NumPy performs element-wise arithmetic efficiently: `+`, `-`, `*`, `/`, `//`, `%`, and `**`.

### Real implementation

In [ ]:
price = np.array([100,200,300])
quantity = np.array([2,3,4])
revenue = price * quantity
print(revenue)

### Practice — 5 Questions

**1.** Add two arrays element-wise.
**2.** Calculate discount prices using multiplication.
**3.** Calculate total revenue from price and quantity arrays.
**4.** Calculate percentage changes between two arrays.
**5.** Calculate compound growth using exponentiation.

In [ ]:
# Practice 1: Add two arrays element-wise.
# Write your solution here


In [ ]:
# Practice 2: Calculate discount prices using multiplication.
# Write your solution here


In [ ]:
# Practice 3: Calculate total revenue from price and quantity arrays.
# Write your solution here


In [ ]:
# Practice 4: Calculate percentage changes between two arrays.
# Write your solution here


In [ ]:
# Practice 5: Calculate compound growth using exponentiation.
# Write your solution here


## 13. Universal Functions (ufuncs)

Universal functions apply mathematical operations element-by-element, such as `sqrt`, `exp`, `log`, `abs`, `round`, `floor`, and `ceil`.

### Real implementation

In [ ]:
x = np.array([1,4,9,16])
print(np.sqrt(x))
print(np.log(x))

### Practice — 5 Questions

**1.** Calculate square roots.
**2.** Calculate absolute values of negative numbers.
**3.** Round decimal values.
**4.** Apply floor and ceiling to prices.
**5.** Calculate exponential values for a small array.

In [ ]:
# Practice 1: Calculate square roots.
# Write your solution here


In [ ]:
# Practice 2: Calculate absolute values of negative numbers.
# Write your solution here


In [ ]:
# Practice 3: Round decimal values.
# Write your solution here


In [ ]:
# Practice 4: Apply floor and ceiling to prices.
# Write your solution here


In [ ]:
# Practice 5: Calculate exponential values for a small array.
# Write your solution here


## 14. Comparison and Boolean Operations

Comparisons create boolean arrays. Use `&`, `|`, and `~` for element-wise boolean logic.

### Real implementation

In [ ]:
marks = np.array([45,67,82,39,91])
print(marks >= 50)
print((marks >= 50) & (marks < 80))

### Practice — 5 Questions

**1.** Find values greater than 50.
**2.** Find values between 40 and 70.
**3.** Find values below 35 or above 90.
**4.** Count how many values satisfy a condition.
**5.** Create a boolean mask for passing students.

In [ ]:
# Practice 1: Find values greater than 50.
# Write your solution here


In [ ]:
# Practice 2: Find values between 40 and 70.
# Write your solution here


In [ ]:
# Practice 3: Find values below 35 or above 90.
# Write your solution here


In [ ]:
# Practice 4: Count how many values satisfy a condition.
# Write your solution here


In [ ]:
# Practice 5: Create a boolean mask for passing students.
# Write your solution here


## 15. Aggregation Functions

Common aggregations include `sum`, `min`, `max`, `mean`, `prod`, `std`, and `var`.

### Real implementation

In [ ]:
sales = np.array([120,150,90,200,175])
print("total:", sales.sum())
print("average:", sales.mean())
print("maximum:", sales.max())

### Practice — 5 Questions

**1.** Find total sales.
**2.** Find minimum and maximum temperature.
**3.** Calculate average marks.
**4.** Calculate the product of all values.
**5.** Calculate standard deviation and variance.

In [ ]:
# Practice 1: Find total sales.
# Write your solution here


In [ ]:
# Practice 2: Find minimum and maximum temperature.
# Write your solution here


In [ ]:
# Practice 3: Calculate average marks.
# Write your solution here


In [ ]:
# Practice 4: Calculate the product of all values.
# Write your solution here


In [ ]:
# Practice 5: Calculate standard deviation and variance.
# Write your solution here


## 16. Statistical Functions

NumPy provides statistics such as median, percentile, standard deviation, variance, and correlation.

### Real implementation

In [ ]:
scores = np.array([45,55,60,72,88,91,95])
print("median:", np.median(scores))
print("75th percentile:", np.percentile(scores,75))

### Practice — 5 Questions

**1.** Calculate median salary.
**2.** Find the 25th percentile of a dataset.
**3.** Find the 90th percentile of exam scores.
**4.** Calculate standard deviation.
**5.** Calculate correlation between two variables using `np.corrcoef`.

In [ ]:
# Practice 1: Calculate median salary.
# Write your solution here


In [ ]:
# Practice 2: Find the 25th percentile of a dataset.
# Write your solution here


In [ ]:
# Practice 3: Find the 90th percentile of exam scores.
# Write your solution here


In [ ]:
# Practice 4: Calculate standard deviation.
# Write your solution here


In [ ]:
# Practice 5: Calculate correlation between two variables using `np.corrcoef`.
# Write your solution here


## 17. Axis Concept

`axis=0` usually operates down rows/column-wise, while `axis=1` operates across columns/row-wise for a 2D array.

### Real implementation

In [ ]:
marks = np.array([[80,70,90],[60,75,85],[95,88,92]])
print("column means:", marks.mean(axis=0))
print("row means:", marks.mean(axis=1))

### Practice — 5 Questions

**1.** Calculate the sum of each column.
**2.** Calculate the average of each row.
**3.** Find the maximum value per column.
**4.** Find the minimum value per row.
**5.** Calculate total sales per product across stores.

In [ ]:
# Practice 1: Calculate the sum of each column.
# Write your solution here


In [ ]:
# Practice 2: Calculate the average of each row.
# Write your solution here


In [ ]:
# Practice 3: Find the maximum value per column.
# Write your solution here


In [ ]:
# Practice 4: Find the minimum value per row.
# Write your solution here


In [ ]:
# Practice 5: Calculate total sales per product across stores.
# Write your solution here


## 18. Sorting

Use `np.sort()` for sorted copies and `argsort()` to get the sorting indices.

### Real implementation

In [ ]:
prices = np.array([500,120,750,300,450])
print(np.sort(prices))
print(np.argsort(prices))

### Practice — 5 Questions

**1.** Sort a salary array ascending.
**2.** Sort an array descending.
**3.** Get indices that would sort an array.
**4.** Sort each row of a matrix.
**5.** Use sorting indices to identify the three cheapest products.

In [ ]:
# Practice 1: Sort a salary array ascending.
# Write your solution here


In [ ]:
# Practice 2: Sort an array descending.
# Write your solution here


In [ ]:
# Practice 3: Get indices that would sort an array.
# Write your solution here


In [ ]:
# Practice 4: Sort each row of a matrix.
# Write your solution here


In [ ]:
# Practice 5: Use sorting indices to identify the three cheapest products.
# Write your solution here


## 19. Searching

`where()`, `searchsorted()`, `argmax()`, `argmin()`, and `nonzero()` help locate values or positions.

### Real implementation

In [ ]:
scores = np.array([55,82,41,90,67])
print(np.where(scores >= 60))
print(np.argmax(scores))
print(np.argmin(scores))

### Practice — 5 Questions

**1.** Find indices where values exceed 50.
**2.** Find the index of the maximum value.
**3.** Find the index of the minimum value.
**4.** Find all non-zero elements.
**5.** Use `searchsorted()` on a sorted array.

In [ ]:
# Practice 1: Find indices where values exceed 50.
# Write your solution here


In [ ]:
# Practice 2: Find the index of the maximum value.
# Write your solution here


In [ ]:
# Practice 3: Find the index of the minimum value.
# Write your solution here


In [ ]:
# Practice 4: Find all non-zero elements.
# Write your solution here


In [ ]:
# Practice 5: Use `searchsorted()` on a sorted array.
# Write your solution here


## 20. Filtering

Boolean masks allow you to select only elements satisfying a condition.

### Real implementation

In [ ]:
sales = np.array([120,450,80,900,300,1500])
high_sales = sales[sales >= 500]
print(high_sales)

### Practice — 5 Questions

**1.** Filter salaries above 50000.
**2.** Filter even numbers.
**3.** Filter temperatures below 20.
**4.** Filter marks between 60 and 90.
**5.** Combine multiple conditions to filter transaction data.

In [ ]:
# Practice 1: Filter salaries above 50000.
# Write your solution here


In [ ]:
# Practice 2: Filter even numbers.
# Write your solution here


In [ ]:
# Practice 3: Filter temperatures below 20.
# Write your solution here


In [ ]:
# Practice 4: Filter marks between 60 and 90.
# Write your solution here


In [ ]:
# Practice 5: Combine multiple conditions to filter transaction data.
# Write your solution here


## 21. Random Numbers

Use `np.random` to generate reproducible random data for simulations and testing.

### Real implementation

In [ ]:
rng = np.random.default_rng(42)
print(rng.integers(1, 101, size=10))
print(rng.random(5))

### Practice — 5 Questions

**1.** Generate 20 random integers from 1 to 100.
**2.** Generate 10 random floats between 0 and 1.
**3.** Set a seed and reproduce the same random values.
**4.** Generate a 3x3 random matrix.
**5.** Simulate 100 dice rolls.

In [ ]:
# Practice 1: Generate 20 random integers from 1 to 100.
# Write your solution here


In [ ]:
# Practice 2: Generate 10 random floats between 0 and 1.
# Write your solution here


In [ ]:
# Practice 3: Set a seed and reproduce the same random values.
# Write your solution here


In [ ]:
# Practice 4: Generate a 3x3 random matrix.
# Write your solution here


In [ ]:
# Practice 5: Simulate 100 dice rolls.
# Write your solution here


## 22. Random Sampling

Random sampling can simulate customers, experiments, games, and datasets. Functions include `choice`, `permutation`, and `shuffle`.

### Real implementation

In [ ]:
rng = np.random.default_rng(42)
customers = np.arange(1,11)
print(rng.choice(customers, size=5, replace=False))

### Practice — 5 Questions

**1.** Select 5 unique customers randomly.
**2.** Select 10 customers with replacement.
**3.** Generate a random permutation of 1–10.
**4.** Shuffle an array.
**5.** Simulate random product selections for 100 transactions.

In [ ]:
# Practice 1: Select 5 unique customers randomly.
# Write your solution here


In [ ]:
# Practice 2: Select 10 customers with replacement.
# Write your solution here


In [ ]:
# Practice 3: Generate a random permutation of 1–10.
# Write your solution here


In [ ]:
# Practice 4: Shuffle an array.
# Write your solution here


In [ ]:
# Practice 5: Simulate random product selections for 100 transactions.
# Write your solution here


## 23. Broadcasting

Broadcasting lets NumPy perform operations on arrays with compatible shapes without manually repeating data.

### Real implementation

In [ ]:
prices = np.array([100,200,300])
discount = 0.10
final_prices = prices * (1-discount)
print(final_prices)

### Practice — 5 Questions

**1.** Apply one discount percentage to every product.
**2.** Add a fixed tax to every price.
**3.** Normalize each column of a matrix.
**4.** Subtract a row vector from every row of a matrix.
**5.** Use broadcasting to calculate distances from several points to one point.

In [ ]:
# Practice 1: Apply one discount percentage to every product.
# Write your solution here


In [ ]:
# Practice 2: Add a fixed tax to every price.
# Write your solution here


In [ ]:
# Practice 3: Normalize each column of a matrix.
# Write your solution here


In [ ]:
# Practice 4: Subtract a row vector from every row of a matrix.
# Write your solution here


In [ ]:
# Practice 5: Use broadcasting to calculate distances from several points to one point.
# Write your solution here


## 24. Missing and Invalid Values

Use `np.nan`, `np.isnan()`, `np.isfinite()`, and related functions to detect problematic numeric data.

### Real implementation

In [ ]:
data = np.array([10,20,np.nan,40,50])
print(np.isnan(data))
print(np.nanmean(data))

### Practice — 5 Questions

**1.** Detect NaN values.
**2.** Calculate mean while ignoring NaN.
**3.** Find finite values.
**4.** Replace NaN with the mean.
**5.** Identify infinite values in a dataset.

In [ ]:
# Practice 1: Detect NaN values.
# Write your solution here


In [ ]:
# Practice 2: Calculate mean while ignoring NaN.
# Write your solution here


In [ ]:
# Practice 3: Find finite values.
# Write your solution here


In [ ]:
# Practice 4: Replace NaN with the mean.
# Write your solution here


In [ ]:
# Practice 5: Identify infinite values in a dataset.
# Write your solution here


## 25. `where()` and Conditional Operations

`np.where(condition, x, y)` performs vectorized if/else logic.

### Real implementation

In [ ]:
marks = np.array([35,55,72,41,90])
result = np.where(marks >= 50, "Pass", "Fail")
print(result)

### Practice — 5 Questions

**1.** Label values as positive/negative.
**2.** Give a 10% discount to products above a threshold.
**3.** Create Pass/Fail labels.
**4.** Replace negative values with zero.
**5.** Create risk categories based on transaction amounts.

In [ ]:
# Practice 1: Label values as positive/negative.
# Write your solution here


In [ ]:
# Practice 2: Give a 10% discount to products above a threshold.
# Write your solution here


In [ ]:
# Practice 3: Create Pass/Fail labels.
# Write your solution here


In [ ]:
# Practice 4: Replace negative values with zero.
# Write your solution here


In [ ]:
# Practice 5: Create risk categories based on transaction amounts.
# Write your solution here


## 26. Set Operations

NumPy set functions include `unique`, `intersect1d`, `union1d`, `setdiff1d`, and `isin`.

### Real implementation

In [ ]:
a = np.array([1,2,2,3,4])
b = np.array([3,4,5,6])
print(np.unique(a))
print(np.intersect1d(a,b))

### Practice — 5 Questions

**1.** Find unique customer IDs.
**2.** Find common IDs between two arrays.
**3.** Find all IDs present in either dataset.
**4.** Find IDs in A but not B.
**5.** Check whether selected product IDs exist in an inventory array.

In [ ]:
# Practice 1: Find unique customer IDs.
# Write your solution here


In [ ]:
# Practice 2: Find common IDs between two arrays.
# Write your solution here


In [ ]:
# Practice 3: Find all IDs present in either dataset.
# Write your solution here


In [ ]:
# Practice 4: Find IDs in A but not B.
# Write your solution here


In [ ]:
# Practice 5: Check whether selected product IDs exist in an inventory array.
# Write your solution here


## 27. Linear Algebra

NumPy's `linalg` module provides matrix multiplication, inverse, determinant, eigenvalues, norms, and solving linear systems.

### Real implementation

In [ ]:
A = np.array([[2,1],[1,3]])
b = np.array([5,7])
x = np.linalg.solve(A,b)
print(x)

### Practice — 5 Questions

**1.** Multiply two matrices using `@`.
**2.** Calculate the determinant of a matrix.
**3.** Calculate a matrix inverse.
**4.** Solve a system of two linear equations.
**5.** Calculate the norm of a vector.

In [ ]:
# Practice 1: Multiply two matrices using `@`.
# Write your solution here


In [ ]:
# Practice 2: Calculate the determinant of a matrix.
# Write your solution here


In [ ]:
# Practice 3: Calculate a matrix inverse.
# Write your solution here


In [ ]:
# Practice 4: Solve a system of two linear equations.
# Write your solution here


In [ ]:
# Practice 5: Calculate the norm of a vector.
# Write your solution here


## 28. Matrix Operations

Matrix-specific operations include transpose, diagonal extraction, trace, and matrix multiplication.

### Real implementation

In [ ]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A.T)
print(np.diag(A))
print(np.trace(A))

### Practice — 5 Questions

**1.** Transpose a matrix.
**2.** Extract its diagonal.
**3.** Calculate its trace.
**4.** Multiply two matrices.
**5.** Create an identity matrix and multiply it by another matrix.

In [ ]:
# Practice 1: Transpose a matrix.
# Write your solution here


In [ ]:
# Practice 2: Extract its diagonal.
# Write your solution here


In [ ]:
# Practice 3: Calculate its trace.
# Write your solution here


In [ ]:
# Practice 4: Multiply two matrices.
# Write your solution here


In [ ]:
# Practice 5: Create an identity matrix and multiply it by another matrix.
# Write your solution here


## 29. Date and Time

NumPy provides `datetime64` and `timedelta64` for array-based date calculations.

### Real implementation

In [ ]:
dates = np.array(['2026-01-01','2026-01-15','2026-02-01'], dtype='datetime64')
print(dates)
print(dates + np.timedelta64(7,'D'))

### Practice — 5 Questions

**1.** Create an array of dates.
**2.** Calculate days between two dates.
**3.** Add 30 days to dates.
**4.** Find the number of days between order and delivery dates.
**5.** Filter dates after a given date.

In [ ]:
# Practice 1: Create an array of dates.
# Write your solution here


In [ ]:
# Practice 2: Calculate days between two dates.
# Write your solution here


In [ ]:
# Practice 3: Add 30 days to dates.
# Write your solution here


In [ ]:
# Practice 4: Find the number of days between order and delivery dates.
# Write your solution here


In [ ]:
# Practice 5: Filter dates after a given date.
# Write your solution here


## 30. Polynomial Operations

NumPy's polynomial functionality can represent and evaluate polynomial equations.

### Real implementation

In [ ]:
coeff = [2, 3, 1]  # 2x² + 3x + 1
x = np.array([0,1,2,3])
print(np.polyval(coeff, x))

### Practice — 5 Questions

**1.** Evaluate a linear polynomial.
**2.** Evaluate a quadratic polynomial for several x values.
**3.** Find polynomial roots.
**4.** Fit a polynomial to sample x/y data using `np.polyfit`.
**5.** Compare predictions from degree-1 and degree-2 fits.

In [ ]:
# Practice 1: Evaluate a linear polynomial.
# Write your solution here


In [ ]:
# Practice 2: Evaluate a quadratic polynomial for several x values.
# Write your solution here


In [ ]:
# Practice 3: Find polynomial roots.
# Write your solution here


In [ ]:
# Practice 4: Fit a polynomial to sample x/y data using `np.polyfit`.
# Write your solution here


In [ ]:
# Practice 5: Compare predictions from degree-1 and degree-2 fits.
# Write your solution here


## 31. Reading and Writing NumPy Data

`.npy` stores one NumPy array; `.npz` can store multiple arrays. These formats preserve NumPy data efficiently.

### Real implementation

In [ ]:
data = np.arange(10)
np.save("practice_data.npy", data)
loaded = np.load("practice_data.npy")
print(loaded)

### Practice — 5 Questions

**1.** Save an array to `.npy`.
**2.** Load an `.npy` file.
**3.** Save two arrays into an `.npz` file.
**4.** Load arrays from `.npz`.
**5.** Create a small dataset, save it, reload it, and verify equality with `np.array_equal`.

In [ ]:
# Practice 1: Save an array to `.npy`.
# Write your solution here


In [ ]:
# Practice 2: Load an `.npy` file.
# Write your solution here


In [ ]:
# Practice 3: Save two arrays into an `.npz` file.
# Write your solution here


In [ ]:
# Practice 4: Load arrays from `.npz`.
# Write your solution here


In [ ]:
# Practice 5: Create a small dataset, save it, reload it, and verify equality with `np.array_equal`.
# Write your solution here


## 32. Vectorization and Performance

Vectorized NumPy operations are generally much faster than Python loops for large numerical workloads.

### Real implementation

In [ ]:
import time
x = np.arange(1_000_000)
start = time.perf_counter()
y = x * 2 + 10
print("vectorized:", time.perf_counter() - start)

### Practice — 5 Questions

**1.** Double one million values without a loop.
**2.** Calculate squares vectorized.
**3.** Replace a Python loop with a NumPy condition.
**4.** Benchmark loop vs vectorized addition.
**5.** Explain from your benchmark why vectorization matters.

In [ ]:
# Practice 1: Double one million values without a loop.
# Write your solution here


In [ ]:
# Practice 2: Calculate squares vectorized.
# Write your solution here


In [ ]:
# Practice 3: Replace a Python loop with a NumPy condition.
# Write your solution here


In [ ]:
# Practice 4: Benchmark loop vs vectorized addition.
# Write your solution here


In [ ]:
# Practice 5: Explain from your benchmark why vectorization matters.
# Write your solution here


## 33. Real-World Sales Analysis

Combine arrays, filtering, statistics, sorting, boolean masks, and broadcasting to analyze business data.

### Real implementation

In [ ]:
rng = np.random.default_rng(10)
price = rng.integers(100,1000,20)
quantity = rng.integers(1,10,20)
revenue = price * quantity
print("Total revenue:", revenue.sum())
print("Average order revenue:", revenue.mean())
print("Top 5 revenues:", np.sort(revenue)[-5:][::-1])

### Practice — 5 Questions

**1.** Find total revenue.
**2.** Find average order value.
**3.** Identify orders above the 75th percentile.
**4.** Find the top 5 transactions.
**5.** Calculate the percentage of transactions above average.

In [ ]:
# Practice 1: Find total revenue.
# Write your solution here


In [ ]:
# Practice 2: Find average order value.
# Write your solution here


In [ ]:
# Practice 3: Identify orders above the 75th percentile.
# Write your solution here


In [ ]:
# Practice 4: Find the top 5 transactions.
# Write your solution here


In [ ]:
# Practice 5: Calculate the percentage of transactions above average.
# Write your solution here


## 34. Real-World Student Analytics

Use NumPy to analyze marks across subjects and students.

### Real implementation

In [ ]:
marks = np.array([
    [78,82,91,70],
    [65,74,80,69],
    [92,88,95,90],
    [55,61,58,64],
    [84,79,87,83]
])
print("Student averages:", marks.mean(axis=1))
print("Subject averages:", marks.mean(axis=0))

### Practice — 5 Questions

**1.** Find each student's average.
**2.** Find each subject's average.
**3.** Identify students with average >= 75.
**4.** Find the highest score in each subject.
**5.** Calculate the overall class average.

In [ ]:
# Practice 1: Find each student's average.
# Write your solution here


In [ ]:
# Practice 2: Find each subject's average.
# Write your solution here


In [ ]:
# Practice 3: Identify students with average >= 75.
# Write your solution here


In [ ]:
# Practice 4: Find the highest score in each subject.
# Write your solution here


In [ ]:
# Practice 5: Calculate the overall class average.
# Write your solution here


## 35. Final Mini-Project — Retail Analytics

This capstone combines array creation, random data generation, arithmetic, filtering, aggregation, sorting, broadcasting, dates, and saving/loading.

### Real implementation

In [ ]:
# Start by designing your 1,000-transaction synthetic dataset.
# Use NumPy arrays for the numerical columns.

### Practice — 5 Questions

**1.** Create the synthetic dataset.
**2.** Calculate transaction revenue.
**3.** Analyze high-value transactions.
**4.** Calculate category-level statistics.
**5.** Produce five business insights from the arrays.

In [ ]:
# Practice 1: Create the synthetic dataset.
# Write your solution here


In [ ]:
# Practice 2: Calculate transaction revenue.
# Write your solution here


In [ ]:
# Practice 3: Analyze high-value transactions.
# Write your solution here


In [ ]:
# Practice 4: Calculate category-level statistics.
# Write your solution here


In [ ]:
# Practice 5: Produce five business insights from the arrays.
# Write your solution here


# Final Capstone — Customer Transaction Analytics System

Create a synthetic dataset of **1,000 transactions** using NumPy only.

Include:
- Customer ID
- Product ID
- Product category
- Unit price
- Quantity
- Discount
- Transaction date

### Required analysis
1. Gross revenue
2. Discount amount
3. Net revenue
4. Average and median order value
5. Standard deviation
6. Top 20 transactions
7. Customers with multiple purchases
8. Category-level revenue
9. 90th percentile transaction value
10. High-value transactions
11. Daily/monthly statistics
12. Missing/invalid-value detection
13. Broadcasting
14. Boolean filtering
15. Sorting/searching
16. Random sampling
17. Save and reload using `.npy` or `.npz`
18. Write 10 business insights

**Rule:** Use NumPy for the core numerical analysis; do not use pandas.


In [ ]:
# Final Project Section 1
# Build your solution here


In [ ]:
# Final Project Section 2
# Build your solution here


In [ ]:
# Final Project Section 3
# Build your solution here


In [ ]:
# Final Project Section 4
# Build your solution here


In [ ]:
# Final Project Section 5
# Build your solution here


# NumPy Completion Checklist

Before marking NumPy complete, make sure you can independently use:

`array`, `arange`, `linspace`, `zeros`, `ones`, `full`, `shape`, `ndim`, `size`, `dtype`, indexing, slicing, boolean masks, `reshape`, `flatten`, `ravel`, transpose, `concatenate`, `vstack`, `hstack`, `split`, copy/view, iteration, vectorized arithmetic, ufuncs, aggregation, statistics, axis, sorting, searching, filtering, random generation, sampling, broadcasting, NaN handling, `where`, set operations, matrix multiplication, `np.linalg`, datetime arrays, polynomial operations, `.npy`/`.npz`, vectorization, and real-world numerical analysis.

**Completion rule:** Finish the final capstone without copying solutions and explain why you used each major NumPy operation.
